"$schema" = 'https://starship.rs/config-schema.json'

format = """
┌─\\($username\\)─\\[$localip\\]─\\[$directory\\]─\\[$git_branch$git_status\\]\\($cmd_duration\\)$fill
└$character
"""

[username]
show_always = true
style_user = "fg:red"
style_root = "fg:red"
format = '[$user]($style)'

[localip]
ssh_only = false
style = "fg:green"
format = '[$localipv4]($style)'
disabled = false

[directory]
style = "fg:yellow"
format = "[$path]($style)"
fish_style_pwd_dir_length = 1 

[git_branch]
symbol = " "
style = "fg:blue"
format = '[$symbol $branch ]($style)'

[git_status]
style = "fg:blue"
format = '[($all_status$ahead_behind) ]($style)'

[cmd_duration]
min_time = 500
style = "fg:purple"
format = '[$duration]($style)'

[fill]
symbol = '─'

[character]
disabled = false
success_symbol = '[](bold fg:yellow)'
error_symbol = '[ ](bold fg:red)'
vimcmd_symbol = ''
vimcmd_replace_one_symbol = '[](bold green)'
vimcmd_replace_symbol = '[](bold green)'
vimcmd_visual_symbol = '[](bold green)'
